# Generated by Django 6.1.1 on 2026-09-23 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id_mensagem', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='mensagens/')),
                ('situacao', models.CharField(max_length=30)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='pessoas.pessoa')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='pessoas.pessoa')),
            ],
        ),
    ]
