# Generated by Django 6.1.1 on 2026-09-23 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=50)),
                ('quant_pessoas', models.PositiveIntegerField()),
                ('horas_ini', models.TimeField()),
                ('horas_final', models.TimeField()),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='apartamentos.apartamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pessoas.morador')),
            ],
        ),
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to='reservas.reserva')),
            ],
        ),
    ]
